[package]
name = "dfngen-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.15.8"
paste = "1.0.14"
rand = "0.8.5"
rand_distr = "0.4.3"
rand_mt = "4.2.2"
text_io = "0.1.12"
